trigger:
  paths:
    include:
      - master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: templates/cypress-steps.yml
    parameters:
    baseUrl: 'http://localhost:4173'