trigger:
  paths:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: "false"
 
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install NPM dependencies'

- task: DeleteFiles@1
    displayName: Delete old Cypress test results
    inputs:
      SourceFolder: $(System.DefaultWorkingDirectory)/cypress/results/
      Contents: '*.*'

- script: npm run cy:verify
  displayName: 'Cypress verify'

- script: npm run cy:info
  displayName: 'Cypress info'

- script: |
    npm install -g wait-on
    npm run start:e2e & wait-on http://localhost:4173 & npm run cy:run-junit-reporter:e2e
  displayName: 'Run Cypress tests'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '/home/vsts/work/1/s/cypress/results/result-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Cypress tests'
    searchFolder: '$(System.DefaultWorkingDirectory)'

//used this as a base https://github.com/cypress-io/cypress-example-kitchensink/blob/master/azure-ci.yml
//and this https://github.com/cypress-io/cypress-example-kitchensink/blob/master/package.json#L40
