trigger:
  paths:
    include:
      - master

pool:
  vmImage: 'windows-2022'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: "false"
 
- task: PowerShell@2
  name: Cypress_Tests
  displayName: 'Install dependencies and run cypress tests'
  inputs:
    targetType: 'inline'
    script: |
      Write-Output 'Install dependencies'
      npm install

      Write-Output 'Attempt to run cypress tests'
      npm run start:e2e

      Write-Output 'Attempt to generate cypress e2e reports'
      npm run cy:run-junit-reporter:e2e

      Write-Output 'Attempt to generate cypress component reports'
      npm run cy:run-junit-reporter:component

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Pipeline.Workspace)/s/PatientPortal/src/Portal.Api/ClientApp/cypress/reports/report-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Cypress tests'
