trigger:
  paths:
    include:
      - master

pool:
  vmImage: 'windows-2022'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: "false"
 
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

- script: npm ci
  displayName: 'Install NPM dependencies'

- script: npm run cy:verify
  displayName: 'Cypress verify'

- script: npm run cy:info
  displayName: 'Cypress info'

- script: |
    npm install -g wait-on
    npm run start:e2e & wait-on http://localhost:4173
    npx cypress run --reporter junit
  displayName: 'Run Cypress tests'

- task: PublishTestResults@2
  displayName: 'Publish test results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/reports/report-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Cypress tests'
