trigger:
  paths:
    include:
      - master

pool:
  vmImage: 'windows-2022'

steps:
- checkout: self
  fetchDepth: 0
  fetchTags: "false"
 

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js'

# Install Node dependencies
- script: npm ci
  displayName: 'Install NPM dependencies'

- script: npm run cy:verify
  displayName: 'Cypress verify'

- script: npm run cy:info
  displayName: 'Cypress info'

- script: |
    npx print-env AGENT
    npx print-env BUILD
    npx print-env SYSTEM
    npm run start & npm run cy:run-junit-reporter:e2e
  displayName: 'Run Cypress tests'






 
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Pipeline.Workspace)/s/PatientPortal/src/Portal.Api/ClientApp/cypress/reports/report-*.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Cypress tests'
