parameters:
  - name: baseUrl
    default: ''
  - name: vmImage
    default: ''

jobs:
  - job: CypressTests
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: 'Install NPM dependencies'

      - script: npm run cy:verify
        displayName: 'Verify Cypress is installed'

      - script: |
          npm install -g wait-on
          npm run start:e2e & wait-on ${{parameters.baseUrl}} & cypress run --reporter junit --config videosFolder=cypress/e2e/videos, screenshotsFolder=cypress/e2e/screenshots
        continueOnError: False
        displayName: 'Run tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '/home/vsts/work/1/s/cypress/results/result-*.xml'
          testRunTitle: 'Cypress tests_$(Build.BuildNumber)'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish screenshots'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/e2e/screenshots'
          ArtifactName: screenshots

      - task: PublishBuildArtifacts@1
        displayName: 'Publish videos'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/e2e/videos'
          ArtifactName: videos


      - script: |
          npm install -g wait-on
          npm run start:e2e & wait-on ${{parameters.baseUrl}} & cypress run -q --component --reporter junit --config videosFolder=cypress/component/videos, screenshotsFolder=cypress/component/screenshots
        continueOnError: False
        displayName: 'Run tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '/home/vsts/work/1/s/cypress/results/result-*.xml'
          testRunTitle: 'Cypress tests_$(Build.BuildNumber)'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish screenshots'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/component/screenshots'
          ArtifactName: screenshots

      - task: PublishBuildArtifacts@1
        displayName: 'Publish videos'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/component/videos'
          ArtifactName: videos

