parameters:
  - name: baseUrl
    default: ''
  - name: vmImage
    default: ''

jobs:
  - job: CypressPrerequisites
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '18.x'
        displayName: 'Install Node.js'

      - script: npm ci
        displayName: 'Install NPM dependencies'

      - script: npm run cy:verify
        displayName: 'Verify Cypress is installed'


  - job: CypressE2ETests
    dependsOn: CypressPrerequisites
    condition: succeeded()
    steps:
      - script: |
          npm install -g wait-on
          npm run start:e2e & wait-on ${{parameters.baseUrl}} & npm run cy:run-junit-reporter:e2e
        continueOnError: True
        displayName: 'Run tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '/home/vsts/work/1/s/cypress/results/e2e/result-*.xml'
          testRunTitle: 'Cypress tests'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish screenshots'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/screenshots/e2e'
          ArtifactName: screenshots

      - task: PublishBuildArtifacts@1
        displayName: 'Publish videos'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/videos/e2e'
          ArtifactName: videos


  - job: CypressComponentTests
    dependsOn: CypressPrerequisites
    condition: succeeded()
    steps:
      - script: |
          npm install -g wait-on
          npm run start:e2e & wait-on ${{parameters.baseUrl}} & npm run cy:run-junit-reporter:component
        continueOnError: True
        displayName: 'Run tests'

      - task: PublishTestResults@2
        displayName: 'Publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '/home/vsts/work/1/s/cypress/results/component/result-*.xml'
          testRunTitle: 'Cypress tests'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          mergeTestResults: true

      - task: PublishBuildArtifacts@1
        displayName: 'Publish screenshots'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/screenshots/component'
          ArtifactName: screenshots

      - task: PublishBuildArtifacts@1
        displayName: 'Publish videos'
        condition: failed()
        continueOnError: True
        inputs:
          PathtoPublish: '/home/vsts/work/1/s/cypress/videos/component'
          ArtifactName: videos

